/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '16. 7. 16 오전 11:17' with Gradle 2.14
 *
 * @author user, @date 16. 7. 16 오전 11:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
